/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/alarm` | `/alarm`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/community_form` | `/community_form`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/crime_reporting` | `/crime_reporting`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dump` | `/dump`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/HeatMap` | `/HeatMap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/report_submission` | `/report_submission`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SOS_support` | `/SOS_support`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/watch` | `/watch`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/alarm` | `/alarm`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/community_form` | `/community_form`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/crime_reporting` | `/crime_reporting`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dump` | `/dump`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/HeatMap` | `/HeatMap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/report_submission` | `/report_submission`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/SOS_support` | `/SOS_support`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/watch` | `/watch`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/alarm${`?${string}` | `#${string}` | ''}` | `/alarm${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/community_form${`?${string}` | `#${string}` | ''}` | `/community_form${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/crime_reporting${`?${string}` | `#${string}` | ''}` | `/crime_reporting${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dump${`?${string}` | `#${string}` | ''}` | `/dump${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/HeatMap${`?${string}` | `#${string}` | ''}` | `/HeatMap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/report_submission${`?${string}` | `#${string}` | ''}` | `/report_submission${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/SOS_support${`?${string}` | `#${string}` | ''}` | `/SOS_support${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/watch${`?${string}` | `#${string}` | ''}` | `/watch${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/alarm` | `/alarm`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/community_form` | `/community_form`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/crime_reporting` | `/crime_reporting`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dump` | `/dump`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/HeatMap` | `/HeatMap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/report_submission` | `/report_submission`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SOS_support` | `/SOS_support`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/watch` | `/watch`; params?: Router.UnknownInputParams; };
    }
  }
}
